version: '3.9'

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    privileged: true
    restart: always
    environment:
      - AP_IFACE=wlan0
      - INTERNET_IFACE=eth0
      - SSID=Infrareveal
    volumes:
       - ./data:/root/pb/pb_data
    entrypoint: ["/root/entrypoint.sh"]
    # entrypoint: /bin/bash
    tty: true
    ports:
      - "8090:8090"
  dashboard:
    image: appademin/infrareveal-dashboard:0.0.3
    restart: always
    ports:
      - "8080:80"

