version: '3.9'

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"  # Equivalent to --net host
    privileged: true       # Equivalent to --privileged
    restart: always        # Equivalent to --restart always
    environment:
      - AP_IFACE=wlan0     # Replace with your Wi-Fi interface
      - INTERNET_IFACE=eth0 # Replace with your internet interface
      - SSID=Infrareveal
    volumes:
       - ./data:/root/pb/pb_data
    entrypoint: ["/root/entrypoint.sh"]
    # entrypoint: /bin/bash
    tty: true
    ports:
      - "8090:8090"
  dashboard:
    image: appademin/infrareveal-dashboard:0.0.3
    restart: always
    ports:
      - "8080:80"

