services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    privileged: true
    restart: always
    environment:
      - AP_IFACE=wlan0
      - INTERNET_IFACE=eth0
      - SSID=Infrareveal
      - PACKET_ACTIVITY_ENABLED=true
      - PACKET_ACTIVITY_BUCKET_MS=50
      - PACKET_ACTIVITY_CHUNK_SECONDS=5
      - PACKET_ACTIVITY_RETENTION_HOURS=24
    volumes:
       - ./data:/root/pb/pb_data
    entrypoint: ["/root/entrypoint.sh"]
    # entrypoint: /bin/bash
    tty: true
    ports:
      - "8090:8090"
  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    restart: always
    ports:
      - "8080:80"
